name: Build and Deploy React App
on:
  push:
    branches: [ main ]
    paths: ['scoreboard/**']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install and Build React
        run: |
          cd scoreboard
          npm install
          npm run build
          cp -r build/* ../
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JEONJOLHYUP }}
          channelId: live
          projectId: jeonjolhyup
- name: Deploy Functions
  run: |
    cd functions
    npm install
    npx firebase deploy --only functions --project jeonjolhyup
